# Generated by Django 5.2.7 on 2025-10-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('AMP_ON', 'Amp On'), ('AMP_OFF', 'Amp Off'), ('TEST_BELL', 'Test Bell')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
            ],
        ),
    ]
