# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_profile_b16'),
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('b1', models.TimeField(blank=True, null=True)),
                ('b2', models.TimeField(blank=True, null=True)),
                ('b3', models.TimeField(blank=True, null=True)),
                ('b4', models.TimeField(blank=True, null=True)),
                ('b5', models.TimeField(blank=True, null=True)),
                ('b6', models.TimeField(blank=True, null=True)),
                ('b7', models.TimeField(blank=True, null=True)),
                ('b8', models.TimeField(blank=True, null=True)),
                ('b9', models.TimeField(blank=True, null=True)),
                ('b10', models.TimeField(blank=True, null=True)),
                ('b11', models.TimeField(blank=True, null=True)),
                ('b12', models.TimeField(blank=True, null=True)),
                ('b13', models.TimeField(blank=True, null=True)),
                ('b14', models.TimeField(blank=True, null=True)),
                ('b15', models.TimeField(blank=True, null=True)),
                ('b16', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='main_current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='pg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('b1', models.TimeField(blank=True, null=True)),
                ('b2', models.TimeField(blank=True, null=True)),
                ('b3', models.TimeField(blank=True, null=True)),
                ('b4', models.TimeField(blank=True, null=True)),
                ('b5', models.TimeField(blank=True, null=True)),
                ('b6', models.TimeField(blank=True, null=True)),
                ('b7', models.TimeField(blank=True, null=True)),
                ('b8', models.TimeField(blank=True, null=True)),
                ('b9', models.TimeField(blank=True, null=True)),
                ('b10', models.TimeField(blank=True, null=True)),
                ('b11', models.TimeField(blank=True, null=True)),
                ('b12', models.TimeField(blank=True, null=True)),
                ('b13', models.TimeField(blank=True, null=True)),
                ('b14', models.TimeField(blank=True, null=True)),
                ('b15', models.TimeField(blank=True, null=True)),
                ('b16', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pg_current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='profile',
            new_name='ke',
        ),
        migrations.RenameModel(
            old_name='current',
            new_name='ke_current',
        ),
    ]
