# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20171004_0818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main',
            new_name='main_blk',
        ),
    ]
