# Generated by Django 2.0.3 on 2018-09-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20171214_1238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main_blk',
            new_name='blk',
        ),
        migrations.DeleteModel(
            name='ke',
        ),
        migrations.DeleteModel(
            name='pg',
        ),
    ]
