from __future__ import unicode_literals

from django.db import models

# Create your models here.
class blk(models.Model):
    """docstring for bells"""
    name = models.CharField(max_length = 50, null=False,unique = True)
    b1 = models.TimeField(blank=True, null=True)
    t1 = models.CharField(max_length = 1, null=True)
    a1 = models.BooleanField(default = False)
    b1_d0 = models.BooleanField(default = False)
    b1_d1 = models.BooleanField(default = False)
    b1_d2 = models.BooleanField(default = False)
    b1_d3 = models.BooleanField(default = False)
    b1_d4 = models.BooleanField(default = False)
    b1_d5 = models.BooleanField(default = False)
    b1_d6 = models.BooleanField(default = False) 
    
    b2 = models.TimeField(blank=True, null=True)
    t2 = models.CharField(max_length = 1, null=True)
    a2 = models.BooleanField(default = False)
    b2_d0 = models.BooleanField(default = False)
    b2_d1 = models.BooleanField(default = False)
    b2_d2 = models.BooleanField(default = False)
    b2_d3 = models.BooleanField(default = False)
    b2_d4 = models.BooleanField(default = False)
    b2_d5 = models.BooleanField(default = False)
    b2_d6 = models.BooleanField(default = False)
    
    b3 = models.TimeField(blank=True, null=True)
    t3 = models.CharField(max_length = 1, null=True)
    a3 = models.BooleanField(default = False)
    b3_d0 = models.BooleanField(default = False)
    b3_d1 = models.BooleanField(default = False)
    b3_d2 = models.BooleanField(default = False)
    b3_d3 = models.BooleanField(default = False)
    b3_d4 = models.BooleanField(default = False)
    b3_d5 = models.BooleanField(default = False)
    b3_d6 = models.BooleanField(default = False)
    
    b4 = models.TimeField(blank=True, null=True)
    t4 = models.CharField(max_length = 1, null=True)
    a4 = models.BooleanField(default = False)
    b4_d0 = models.BooleanField(default = False)
    b4_d1 = models.BooleanField(default = False)
    b4_d2 = models.BooleanField(default = False)
    b4_d3 = models.BooleanField(default = False)
    b4_d4 = models.BooleanField(default = False)
    b4_d5 = models.BooleanField(default = False)
    b4_d6 = models.BooleanField(default = False)

    b5 = models.TimeField(blank=True, null=True)
    t5 = models.CharField(max_length = 1, null=True)
    a5 = models.BooleanField(default = False)
    b5_d0 = models.BooleanField(default = False)
    b5_d1 = models.BooleanField(default = False)
    b5_d2 = models.BooleanField(default = False)
    b5_d3 = models.BooleanField(default = False)
    b5_d4 = models.BooleanField(default = False)
    b5_d5 = models.BooleanField(default = False)
    b5_d6 = models.BooleanField(default = False)

    b6 = models.TimeField(blank=True, null=True)
    t6 = models.CharField(max_length = 1, null=True)
    a6 = models.BooleanField(default = False)
    b6_d0 = models.BooleanField(default = False)
    b6_d1 = models.BooleanField(default = False)
    b6_d2 = models.BooleanField(default = False)
    b6_d3 = models.BooleanField(default = False)
    b6_d4 = models.BooleanField(default = False)
    b6_d5 = models.BooleanField(default = False)
    b6_d6 = models.BooleanField(default = False)

    b7 = models.TimeField(blank=True, null=True)
    t7 = models.CharField(max_length = 1, null=True)
    a7 = models.BooleanField(default = False)
    b7_d0 = models.BooleanField(default = False)
    b7_d1 = models.BooleanField(default = False)
    b7_d2 = models.BooleanField(default = False)
    b7_d3 = models.BooleanField(default = False)
    b7_d4 = models.BooleanField(default = False)
    b7_d5 = models.BooleanField(default = False)
    b7_d6 = models.BooleanField(default = False)

    b8 = models.TimeField(blank=True, null=True)
    t8 = models.CharField(max_length = 1, null=True)
    a8 = models.BooleanField(default = False)
    b8_d0 = models.BooleanField(default = False)
    b8_d1 = models.BooleanField(default = False)
    b8_d2 = models.BooleanField(default = False)
    b8_d3 = models.BooleanField(default = False)
    b8_d4 = models.BooleanField(default = False)
    b8_d5 = models.BooleanField(default = False)
    b8_d6 = models.BooleanField(default = False)

    b9 = models.TimeField(blank=True, null=True)
    t9 = models.CharField(max_length = 1, null=True)
    a9 = models.BooleanField(default = False)
    b9_d0 = models.BooleanField(default = False)
    b9_d1 = models.BooleanField(default = False)
    b9_d2 = models.BooleanField(default = False)
    b9_d3 = models.BooleanField(default = False)
    b9_d4 = models.BooleanField(default = False)
    b9_d5 = models.BooleanField(default = False)
    b9_d6 = models.BooleanField(default = False)

    b10 = models.TimeField(blank=True, null=True)
    t10 = models.CharField(max_length = 1, null=True)
    a10 = models.BooleanField(default = False)
    b10_d0 = models.BooleanField(default = False)
    b10_d1 = models.BooleanField(default = False)
    b10_d2 = models.BooleanField(default = False)
    b10_d3 = models.BooleanField(default = False)
    b10_d4 = models.BooleanField(default = False)
    b10_d5 = models.BooleanField(default = False)
    b10_d6 = models.BooleanField(default = False)

    b11 = models.TimeField(blank=True, null=True)
    t11 = models.CharField(max_length = 1, null=True)
    a11 = models.BooleanField(default = False)
    b11_d0 = models.BooleanField(default = False)
    b11_d1 = models.BooleanField(default = False)
    b11_d2 = models.BooleanField(default = False)
    b11_d3 = models.BooleanField(default = False)
    b11_d4 = models.BooleanField(default = False)
    b11_d5 = models.BooleanField(default = False)
    b11_d6 = models.BooleanField(default = False)

    b12 = models.TimeField(blank=True, null=True)
    t12 = models.CharField(max_length = 1, null=True)
    a12 = models.BooleanField(default = False)
    b12_d0 = models.BooleanField(default = False)
    b12_d1 = models.BooleanField(default = False)
    b12_d2 = models.BooleanField(default = False)
    b12_d3 = models.BooleanField(default = False)
    b12_d4 = models.BooleanField(default = False)
    b12_d5 = models.BooleanField(default = False)
    b12_d6 = models.BooleanField(default = False)

    b13 = models.TimeField(blank=True, null=True)
    t13 = models.CharField(max_length = 1, null=True)
    a13 = models.BooleanField(default = False)
    b13_d0 = models.BooleanField(default = False)
    b13_d1 = models.BooleanField(default = False)
    b13_d2 = models.BooleanField(default = False)
    b13_d3 = models.BooleanField(default = False)
    b13_d4 = models.BooleanField(default = False)
    b13_d5 = models.BooleanField(default = False)
    b13_d6 = models.BooleanField(default = False)

    b14 = models.TimeField(blank=True, null=True)
    t14 = models.CharField(max_length = 1, null=True)
    a14 = models.BooleanField(default = False)
    b14_d0 = models.BooleanField(default = False)
    b14_d1 = models.BooleanField(default = False)
    b14_d2 = models.BooleanField(default = False)
    b14_d3 = models.BooleanField(default = False)
    b14_d4 = models.BooleanField(default = False)
    b14_d5 = models.BooleanField(default = False)
    b14_d6 = models.BooleanField(default = False)

    b15 = models.TimeField(blank=True, null=True)
    t15 = models.CharField(max_length = 1, null=True)
    a15 = models.BooleanField(default = False)
    b15_d0 = models.BooleanField(default = False)
    b15_d1 = models.BooleanField(default = False)
    b15_d2 = models.BooleanField(default = False)
    b15_d3 = models.BooleanField(default = False)
    b15_d4 = models.BooleanField(default = False)
    b15_d5 = models.BooleanField(default = False)
    b15_d6 = models.BooleanField(default = False)

    b16 = models.TimeField(blank=True, null=True)
    t16 = models.CharField(max_length = 1, null=True)
    a16 = models.BooleanField(default = False)
    b16_d0 = models.BooleanField(default = False)
    b16_d1 = models.BooleanField(default = False)
    b16_d2 = models.BooleanField(default = False)
    b16_d3 = models.BooleanField(default = False)
    b16_d4 = models.BooleanField(default = False)
    b16_d5 = models.BooleanField(default = False)
    b16_d6 = models.BooleanField(default = False)

    b17 = models.TimeField(blank=True, null=True)
    t17 = models.CharField(max_length = 1, null=True)
    a17 = models.BooleanField(default = False)
    b17_d0 = models.BooleanField(default = False)
    b17_d1 = models.BooleanField(default = False)
    b17_d2 = models.BooleanField(default = False)
    b17_d3 = models.BooleanField(default = False)
    b17_d4 = models.BooleanField(default = False)
    b17_d5 = models.BooleanField(default = False)
    b17_d6 = models.BooleanField(default = False)

    b18 = models.TimeField(blank=True, null=True)
    t18 = models.CharField(max_length = 1, null=True)
    a18 = models.BooleanField(default = False)
    b18_d0 = models.BooleanField(default = False)
    b18_d1 = models.BooleanField(default = False)
    b18_d2 = models.BooleanField(default = False)
    b18_d3 = models.BooleanField(default = False)
    b18_d4 = models.BooleanField(default = False)
    b18_d5 = models.BooleanField(default = False)
    b18_d6 = models.BooleanField(default = False)

    b19 = models.TimeField(blank=True, null=True)
    t19 = models.CharField(max_length = 1, null=True)
    a19 = models.BooleanField(default = False)
    b19_d0 = models.BooleanField(default = False)
    b19_d1 = models.BooleanField(default = False)
    b19_d2 = models.BooleanField(default = False)
    b19_d3 = models.BooleanField(default = False)
    b19_d4 = models.BooleanField(default = False)
    b19_d5 = models.BooleanField(default = False)
    b19_d6 = models.BooleanField(default = False)

    b20 = models.TimeField(blank=True, null=True)
    t20 = models.CharField(max_length = 1, null=True)
    a20 = models.BooleanField(default = False)
    b20_d0 = models.BooleanField(default = False)
    b20_d1 = models.BooleanField(default = False)
    b20_d2 = models.BooleanField(default = False)
    b20_d3 = models.BooleanField(default = False)
    b20_d4 = models.BooleanField(default = False)
    b20_d5 = models.BooleanField(default = False)
    b20_d6 = models.BooleanField(default = False)


    b21 = models.TimeField(blank=True, null=True)
    t21 = models.CharField(max_length = 1, null=True)
    a21 = models.BooleanField(default = False)
    b21_d0 = models.BooleanField(default = False)
    b21_d1 = models.BooleanField(default = False)
    b21_d2 = models.BooleanField(default = False)
    b21_d3 = models.BooleanField(default = False)
    b21_d4 = models.BooleanField(default = False)
    b21_d5 = models.BooleanField(default = False)
    b21_d6 = models.BooleanField(default = False)

    b22 = models.TimeField(blank=True, null=True)
    t22 = models.CharField(max_length = 1, null=True)
    a22 = models.BooleanField(default = False)
    b22_d0 = models.BooleanField(default = False)
    b22_d1 = models.BooleanField(default = False)
    b22_d2 = models.BooleanField(default = False)
    b22_d3 = models.BooleanField(default = False)
    b22_d4 = models.BooleanField(default = False)
    b22_d5 = models.BooleanField(default = False)
    b22_d6 = models.BooleanField(default = False)

    b23 = models.TimeField(blank=True, null=True)
    t23 = models.CharField(max_length = 1, null=True)
    a23 = models.BooleanField(default = False)
    b23_d0 = models.BooleanField(default = False)
    b23_d1 = models.BooleanField(default = False)
    b23_d2 = models.BooleanField(default = False)
    b23_d3 = models.BooleanField(default = False)
    b23_d4 = models.BooleanField(default = False)
    b23_d5 = models.BooleanField(default = False)
    b23_d6 = models.BooleanField(default = False)

    b24 = models.TimeField(blank=True, null=True)
    t24 = models.CharField(max_length = 1, null=True)
    a24 = models.BooleanField(default = False)
    b24_d0 = models.BooleanField(default = False)
    b24_d1 = models.BooleanField(default = False)
    b24_d2 = models.BooleanField(default = False)
    b24_d3 = models.BooleanField(default = False)
    b24_d4 = models.BooleanField(default = False)
    b24_d5 = models.BooleanField(default = False)
    b24_d6 = models.BooleanField(default = False)

    b25 = models.TimeField(blank=True, null=True)
    t25 = models.CharField(max_length = 1, null=True)
    a25 = models.BooleanField(default = False)
    b25_d0 = models.BooleanField(default = False)
    b25_d1 = models.BooleanField(default = False)
    b25_d2 = models.BooleanField(default = False)
    b25_d3 = models.BooleanField(default = False)
    b25_d4 = models.BooleanField(default = False)
    b25_d5 = models.BooleanField(default = False)
    b25_d6 = models.BooleanField(default = False)

    b26 = models.TimeField(blank=True, null=True)
    t26 = models.CharField(max_length = 1, null=True)
    a26 = models.BooleanField(default = False)
    b26_d0 = models.BooleanField(default = False)
    b26_d1 = models.BooleanField(default = False)
    b26_d2 = models.BooleanField(default = False)
    b26_d3 = models.BooleanField(default = False)
    b26_d4 = models.BooleanField(default = False)
    b26_d5 = models.BooleanField(default = False)
    b26_d6 = models.BooleanField(default = False)

    b27 = models.TimeField(blank=True, null=True)
    t27 = models.CharField(max_length = 1, null=True)
    a27 = models.BooleanField(default = False)
    b27_d0 = models.BooleanField(default = False)
    b27_d1 = models.BooleanField(default = False)
    b27_d2 = models.BooleanField(default = False)
    b27_d3 = models.BooleanField(default = False)
    b27_d4 = models.BooleanField(default = False)
    b27_d5 = models.BooleanField(default = False)
    b27_d6 = models.BooleanField(default = False)

    b28 = models.TimeField(blank=True, null=True)
    t28 = models.CharField(max_length = 1, null=True)
    a28 = models.BooleanField(default = False)
    b28_d0 = models.BooleanField(default = False)
    b28_d1 = models.BooleanField(default = False)
    b28_d2 = models.BooleanField(default = False)
    b28_d3 = models.BooleanField(default = False)
    b28_d4 = models.BooleanField(default = False)
    b28_d5 = models.BooleanField(default = False)
    b28_d6 = models.BooleanField(default = False)

class main_current(models.Model):
    """docstring for current"""
    name = models.CharField(max_length = 50,unique = True)
class pg_current(models.Model):
    """docstring for current"""
    name = models.CharField(max_length = 50,unique = True)

class ke_current(models.Model):
    """docstring for current"""
    name = models.CharField(max_length = 50,unique = True)